### ISSUE TITLE
Build error!!!

### ISSUE THREAD

**Issue by StingNguyen** [transloadit/node-sdk#103]
W20210318-14:32:08.970(7)? (STDERR)   return Number(process.hrtime.bigint() / 1000000n)
W20210318-14:32:08.970(7)? (STDERR)                                           ^^^^^^^
W20210318-14:32:08.970(7)? (STDERR) 
W20210318-14:32:08.971(7)? (STDERR) SyntaxError: Invalid or unexpected token
W20210318-14:32:08.971(7)? (STDERR)     at createScript (vm.js:80:10)

**Comment by kvz** [comment]
Hi there, what version are you on? Did you recently upgrade? Can you share more snippets how you run and use the sdk? We recently launched v3, breaking a lot of api surface, so perhaps it is related?

**Comment by StingNguyen** [comment]
hello @kvz , and i have not upgrade(first time), and 
my env:
Nodejs: v10.23.3
Meteor: 1.8.1

just import it: import Transloadit from 'transloadit';

**Comment by mifi** [comment]
Are you running any transpilation of the code? I think it is struggling with the bigint literal (`1000000n`), but this is supported on node 10, so I'm not sure why it's failing for you unless you're transpiling code.

**Comment by StingNguyen** [comment]
dear @mifi , thank you, i downgrade to 2.0.10 version

**Comment by mifi** [comment]
Ok. Let me know if you need assistance upgrading to v3. There will probably be many nice features and benefits of using v3 in the future. v2 will probably not see any big updates.

**Comment by StingNguyen** [comment]
Yeah, now The V2 have enough with me. Thank your support!
