### ISSUE TITLE
readme low visibility in github dark mode

### ISSUE THREAD

**Issue by juliangruber** [transloadit/node-sdk#109]
<img width="851" alt="Screenshot 2021-04-26 at 13 09 47" src="https://user-images.githubusercontent.com/10247/116073450-b6f5de00-a690-11eb-8f14-5d6c7b90ee86.png">

GitHub recently implemented native dark mode, where the contrast on the logo type is low.

**Comment by mifi** [comment]
ah, maybe we should just put a white background around the logo

**Comment by mifi** [comment]
fixd
