### ISSUE TITLE
 RequestError: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by ram-livwell** [transloadit/node-sdk#118]
Im using node version is `14.17.4` and npm version is `6.14.14`

I'm  to trying use **`transloadit`** on the local machine. But keep throwing an error.

```
RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous> (/home/ram/code/sample/node_modules/got/dist/source/core/index.js:956:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.origin.emit (/home/ram/code/sample/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1628081393403,
    socket: 1628081393405,
    lookup: 1628081393407,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1628081393408,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 2,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 5
    }
  }
}
```

even I tried to check result  `host api2.transloadit.com`

```
api2.transloadit.com has address 3.0.62.44
api2.transloadit.com has address 18.136.113.29
api2.transloadit.com has address 3.0.156.156
```
and also checked results of  `npm ls got`
```
ram@1.0.0 /home/ram/code/sample
`-- transloadit@3.0.2
  `-- got@11.8.2
```
  
  I tried on 4 local machines but unfortunately I got same error on all the machines
  everything looks perfect but still facing issues.

**Comment by kvz** [comment]
What does your code look like? Specifically the (endpoint) configuration passed to this sdk?

**Comment by ram-livwell** [comment]
here is my code
I have added auth and secret using 
```
const transloadit = new Transloadit({
    authKey: "XXXXXXXXXXXXXXXXXX",
    authSecret: "XXXXXXXXXXXXXXXXX"
})
```

```
async generateTransloadVideoUrl(videoUrl) {
    try {
        const options = {
            params: {
                steps: {
                    imported: {
                        robot: '/http/import',
                        url: videoUrl,
                    },
                    android_encoded: {
                        use: 'imported',
                        robot: '/video/encode',
                        result: true,
                        ffmpeg_stack: 'v4.3.1',
                        preset: 'android',
                        // width: 640,
                        width: 640,
                        height: 480,
                        // height: 1138,
                        turbo: true,
                      },
                      watermarked: {
                        use: 'android_encoded',
                        robot: '/video/encode',
                        result: true,
                        ffmpeg_stack: 'v4.3.1',
                        preset: 'ipad-high',
                        turbo: true,
                        watermark_opacity: 0.7,
                        watermark_position: 'top-right',
                        watermark_size: '15%',
                        watermark_url: 'https://lw-reels-media-xxxx.s3.ap-southeast-1.amazonaws.com/logo_white.png',
                        watermark_x_offset: -350,
                        watermark_y_offset: 90,
                      },
                      
                    exported: {
                        use: ['watermarked'],
                        robot: '/s3/store',
                        credentials: 'lw-reels-media-xxxx',
                        url_prefix: 'https://lw-reels-media-xxxx.s3.ap-south-1.amazonaws.com/',
                        path: "${file.name}"
                    },
                }
            }
        }
        const result = await transloadit.createAssembly(options)
        console.log({ result });
        return result
    } catch (error) {
        consolelog("error",error,false);
        throw error;
    }
}
```
every 30mins we are doing a batch process. Per batch, we are processing 5 videos. But for testing, I'm checking with only one video.

**Comment by mifi** [comment]
@ram-livwell do you have any other packages than `transloadit` in your project? In particular do you have any of these:

`agent-base`
`http-proxy-agent`
`https-proxy-agent`
`pac-proxy-agent`
`socks-proxy-agent`

You can run `yarn why ...` for each of these to check, in particular `yarn why node-agent-base`. If you're using npm you can search your node_modules folder.

If you have any of those, can you try to upgrade them? It seems like they mess with ([monkey patch](https://github.com/TooTallNate/node-agent-base/blob/1aaf316cc3f7e3bad0616d42b483da61416406fd/patch-core.js)) internal node.js functions causing problems for http requests.

I think if you have 6.0.2 of node-agent-base [this should be solved](https://github.com/TooTallNate/node-agent-base/commit/33af5450edd1d99951a8d27a656723f9668160b0)

Some links:
- https://github.com/sindresorhus/got/issues/951
- https://github.com/TooTallNate/node-agent-base

**Comment by ram-livwell** [comment]
@mifi yes I do have other modules along with `transloadit` and I've gone through my `node_modules` folder there I found 
`agent-base`
 `https-proxy-agent`.

**Comment by mifi** [comment]
Which version are those? can you try to upgrade agent-base to 6.0.2?

**Comment by ram-livwell** [comment]
how do I check the version of those modules???

**Comment by juliangruber** [comment]
`npm ls ${module}`

**Comment by ram-livwell** [comment]
@mifi @juliangruber here is the output
```
npm ls agent-base 

ram@1.0.0 /home/ram/code/sample
+-- fcm-node@1.5.2
| `-- https-proxy-agent@2.2.4
|   `-- agent-base@4.3.0 
`-- googleapis@48.0.0
  +-- google-auth-library@5.10.1
  | `-- gaxios@2.3.4
  |   `-- https-proxy-agent@5.0.0
  |     `-- agent-base@6.0.2 
  `-- googleapis-common@3.2.2
    `-- gaxios@2.3.4
      `-- https-proxy-agent@5.0.0
        `-- agent-base@6.0.2 
```

**Comment by ram-livwell** [comment]
@mifi yes I updated to agent-base to 6.0.2 but still same error

**Comment by mifi** [comment]
Thanks. Seems like your fcm-node@1.5.2 depends on agent-base@4.3.0 so it will still monkey patch the node.js core module, causing this issue. https://github.com/jlcvp/fcm-node seems to be deprecated and not updated in a while. Is it possible that you can instead use [google's official node module](https://github.com/firebase/firebase-admin-node) for [FCM](https://firebase.google.com/docs/reference/admin/node/admin.messaging)?

Alternatively you can try to upgrade fcm-node to latest 1.6.1 and also https-proxy-agent to 5.0.0

**Comment by ram-livwell** [comment]
@mifi I updated to fcm-node@1.6.1 solved my problem. many thanks for you finding quick  root casuse.

**Comment by mifi** [comment]
Great!
