### ISSUE TITLE
Is it possible to register a remote file on s3 with the node SDK client?

### ISSUE THREAD

**Issue by juliussss** [transloadit/node-sdk#4]
Hi guys,

Just wondering if it is possible to use the Node SDK to pipe a file that exists in an AWS S3 bucket?

```javascript
TransloaditClient.addFile(name, path)
TransloaditClient.addStream(name, stream)

// potential public method
TransloaditClient.addURL(name, url)
```

Alternatively I was thinking the only option is to build a template (using the SDK) that calls the `/s3/import` robot API.

Any help appreciated, thanks!

**Comment by tim-kos** [comment]
Not right now with an addUrl method, as that is not necessary since you could use the /s3/import or /http/import robot. What would be the advantage of an addUrl method over this?

**Comment by tim-kos** [comment]
Closing this as wontfix.
