### ISSUE TITLE
SSL secured API communication

### ISSUE THREAD

**Issue by seb0zz** [transloadit/node-sdk#5]
As far as I can see the default protocol for API communication is http and not https. Does this have any reason? It would be great if it would be possible to be able to configure https usage.

If you don't have objections I would create a pull request for this feature.

**Comment by kvz** [comment]
I'd personally be in favor! @tim-kos / @acconut?

**Comment by Acconut** [comment]
I'm not aware of any reason why we should prefer HTTP over HTTPS. Please create a PR, @seb0zz
