### ISSUE TITLE
support tus with tus-js-client

### ISSUE THREAD

**Issue by ifedapoolarewaju** [transloadit/node-sdk#52]
are there any reasons why this is not implemented yet? I'd be happy to take on this task

**Comment by tim-kos** [comment]
No reasons, go ahead!

**Comment by kvz** [comment]
Ah, yes, please do!! I think we can then upgrade transloadify and tick another box:

<img width="765" alt="screen shot 2018-05-08 at 11 31 41" src="https://user-images.githubusercontent.com/26752/39749594-6a07e374-52b3-11e8-90ef-fcc18170107.png">

https://transloadit.com/blog/2017/11/tus-in-production/
