### ISSUE TITLE
Refactor Examples

### ISSUE THREAD

**Issue by tim-kos** [transloadit/node-sdk#58]
- [ ] Some nice Christmas tree: https://github.com/transloadit/node-sdk/blob/master/examples/fetch_costs_of_all_assemblies_in_timeframe.js#L24
- [ ] unnecessary `self`: https://github.com/transloadit/node-sdk/blob/master/examples/fetch_costs_of_all_assemblies_in_timeframe.js#L24
- [ ] Error handling in all examples should likely mimic the one in the README.md. For instance: https://github.com/transloadit/node-sdk/blob/master/examples/upload_a_file.js

**Comment by mifi** [comment]
This will be resolved once #87 is merged

**Comment by mifi** [comment]
Now released [v.3.0.0-rc.1](https://github.com/transloadit/node-sdk/releases/tag/v3.0.0-rc.1)!
