### ISSUE TITLE
Typings file

### ISSUE THREAD

**Issue by spacemandev-git** [transloadit/node-sdk#78]
Please include a typings file for typescript !

**Comment by kvz** [comment]
We'll consider this for our next big rewrite as well (as https://github.com/transloadit/node-sdk/issues/79) :)

**Comment by mifi** [comment]
This will be resolved in #87

**Comment by mifi** [comment]
Now released [v.3.0.0-rc.1](https://github.com/transloadit/node-sdk/releases/tag/v3.0.0-rc.1)!
