### ISSUE TITLE
Promisify the function call

### ISSUE THREAD

**Issue by spacemandev-git** [transloadit/node-sdk#79]
Please provide functions that return promises not take in callbacks

**Comment by kvz** [comment]
Thanks for pointing this out, yes, rewriting the node-sdk is on our todo, PRs are welcome too. In the meantime, you can use `promiseFunc = util.promisify(callbackFunc)` to work around this. `bind()`ing to the client may be necessary.

**Comment by mifi** [comment]
This will be resolved once #87 is merged

**Comment by mifi** [comment]
Now released [v.3.0.0-rc.1](https://github.com/transloadit/node-sdk/releases/tag/v3.0.0-rc.1)!
